var quotes = [
  "Nobody goes undefeated all the time. If you can pick up after a crushing defeat, and go on to win again, you are going to be a champion some day! – Kumara Sangakkara",
  "Every batsman surveys the field before taking strike, and usually the fielders get imprinted on his mind. I don’t see the fielders, I only see the gaps! – Ricky Ponting",
  "People throw stones at you and you convert them into milestones. – Sachin Tendulkar",
  "Every morning I woke up, I believed that I could score runs for India. – Sourav Ganguly",
  "Never give up; just absolutely never give up. – Shane Warne",
  "First of all, convince yourself that you are the best because the rest of your life is going to go proving this to others. - Wasim Akram",
  "Enjoy the game & Chase your dreams. Dreams do come true. – Sachin Tendulkar",
  "Compromise for your Dream but never Compromise on your Dream. – Imran Khan",
  "Finishing is one of the most difficult things to do in cricket. A player can't be a finisher in just 6 months or one year. You have to be used to that responsibility. - MS Dhoni",
  "Any active sportsman has to be very focused; you've got to be in the right frame of mind. If your energy is diverted in various directions, you do not achieve the results. - Sachin Tendulkar",
  "I need to know when to switch on and switch off: and the rest of the things happen around that. - Sachin Tendulkar",
  "Cricket is not rocket science. Bowlers often get wickets through perseverance, accuracy and being patient rather than trying to blast opposition teams out. - Andrew Strauss",
  "So I never forget how lucky I am. That's the reason above all else why I'm determined to keep enjoying cricket, whatever the wins or the losses. As long as I do that then the runs will come. - Andrew Strauss",
  "Cricket is 90-95 per cent mental. To score runs, you've got to feel good about yourself. - Andrew Strauss",
  "Quite honestly, cricket is same at all levels. It's a game of bat and ball. - K.L. Rahul",
  "The more cricket you play in your head, the less you perform on the field. So let cricket, the sport, be on the field. - K.L. Rahul",
  "I have had to work really hard at white-ball cricket. It doesn't come naturally to me, I was a slow batsman; I worked hard on my game and fitness. - K.L. Rahul",
  "Nothing is easy in cricket. Maybe when you watch it on TV, it looks easy. But it is not. You have to use your brain and time the ball. - Rohit Sharma",
  "It's always been the most important thing for me to enjoy my cricket. - AB de Villiers",
  "For my part, I am not a great believer in bad luck on the cricket field, in business - in fact, in any walk of life. - AB de Villiers",
  "Physically and mentally, it's quite hard. But I'm playing cricket for England. It's what I dream about doing. - Alastair Cook",
  "No matter how much cricket you have played you are always learning. - Alastair Cook",
  "My approach to cricket has been reasonably simple: it was about giving everything to the team, it was about playing with dignity and it was about upholding the spirit of the game. - Rahul Dravid",
  "I think we judge talent wrong. We judge talent by people's ability to strike a cricket ball. The sweetness, the timing. Things like determination, courage, discipline, temperament, these are also talent. - Rahul Dravid",
  "To me, it doesn't matter how good you are. Sport is all about playing and competing. Whatever you do in cricket and in sport, enjoy it, be positive and try to win. - Ian Botham",
];
